name: 'install-dependencies'
description: 'Checks out the repository and installs dependencies.'
runs:
  using: "composite"
  steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        shell: bash
