name: Checks

# This action works with pull requests and pushes on the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Check Linter
        run: npm run lint-check
      - name: Check Formatter
        run: npm run format-check
